spring:
    application:
        name: sit-exercise
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
    datasource:
        url: ${MSSQL_SIT_EXERCISE_JDBC_URL}
        username: ${MSSQL_SIT_EXERCISE_USERNAME}
        password: ${MSSQL_SIT_EXERCISE_PASSWORD}
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

# OpenApi
springdoc:
    swagger-ui:
        path: /swagger.html
        disable-swagger-default-url: true
        defaultModelsExpandDepth: 4
        show-extensions: true
        show-common-extensions: true

logging:
    level:
        org:
            springframework:
                security: trace

# Distributed Tracing
management:
    otlp:
        tracing:
            endpoint: http://localhost:4318/v1/traces
    tracing:
        sampling:
            probability: 1
